# Generated by Django 3.2.19 on 2023-05-10 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumnos_matricula'),
        ('datos', '0006_auto_20230509_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='alumnos.alumnos', verbose_name='Alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos',
            name='tipo',
            field=models.CharField(choices=[('', 'Elige el tipo'), ('SS', 'Servicio Social'), ('PP', 'Practicas Profecionales')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='carta_aceptacion',
            field=models.FileField(default=1, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten documentos PDF')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='carta_liberacion',
            field=models.FileField(default=1, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten documentos PDF')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha_termino',
            field=models.DateField(default='2023-01-01', max_length=10, verbose_name='Fecha de termino'),
            preserve_default=False,
        ),
    ]
