# Generated by Django 3.2.19 on 2023-05-10 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_auto_20230509_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='carta_aceptacion',
            field=models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten documentos PDF')]),
        ),
        migrations.AlterField(
            model_name='datos',
            name='carta_liberacion',
            field=models.FileField(default=2, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten documentos PDF')]),
            preserve_default=False,
        ),
    ]
