# Generated by Django 3.2.19 on 2023-05-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_auto_20230510_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha_termino',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Fecha de termino'),
        ),
    ]
