# Generated by Django 3.2.19 on 2023-05-10 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_alter_datos_fecha_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='carta_liberacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten documentos PDF')]),
        ),
    ]
