# Generated by Django 3.2.19 on 2023-05-10 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_alter_datos_carta_liberacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='carta_liberacion',
            field=models.FileField(default=1, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Sólo se permiten documentos PDF')]),
            preserve_default=False,
        ),
    ]
