# Generated by Django 3.2.19 on 2023-06-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        ('datos', '0012_datos_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='instituciones.unidadacademica', verbose_name='Unidad Académica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituciones.institucion', verbose_name='Institución'),
        ),
    ]
