# Generated by Django 3.2.19 on 2023-05-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_evaluacionfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionfinal',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Calificación'),
        ),
    ]
