# Generated by Django 3.2.19 on 2023-06-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumnos_programa_academico'),
        ('asesores', '0003_alter_asesores_id'),
        ('reportes', '0004_reporte_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alumno', to='alumnos.alumnos', verbose_name='Alumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asesor', to='asesores.asesores', verbose_name='Asesor')),
            ],
        ),
    ]
