# Generated by Django 3.2.19 on 2023-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20230508_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
    ]
