# Generated by Django 3.2.19 on 2023-06-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumnos_matricula'),
    ]

    operations = [
    ]
