# Generated by Django 3.2.19 on 2023-05-09 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('ap_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('fecha_nac', models.DateField(max_length=10, verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(upload_to='perfil', verbose_name='Foto de perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
