# Generated by Django 3.2.19 on 2023-05-10 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ususarios', '0003_auto_20230510_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='curp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(code='curp_invalido', message='La CURP no tiene un formato válido.', regex='/^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$/')], verbose_name='C.U.R.P.'),
        ),
    ]
