# Generated by Django 3.2.19 on 2023-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('ap_materno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('institucion', models.CharField(max_length=30, verbose_name='Institución')),
                ('puesto', models.CharField(max_length=30, verbose_name='Puesto')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('no_serie', models.CharField(max_length=20, verbose_name='No. Serie')),
                ('certificado', models.CharField(max_length=3000, verbose_name='Certificado')),
                ('contrasena_cert', models.CharField(max_length=20, verbose_name='Contraseña de Certificado')),
                ('tipo', models.CharField(choices=[('', 'Elige el tipo'), ('INT', 'Interno'), ('EXT', 'Externo')], max_length=3)),
            ],
        ),
    ]
