# Generated by Django 3.2.19 on 2023-06-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_alter_asesores_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
